export function TopMessage() {
  return (
    <header className="text-left">
      PREZADOS MORADORES,<br /><br />
COMO ACUMULAM MUITOS PANFLETOS E
LIXOS QUE O VENTO TRAZ PARA O PRÉDIO,
EXISTE A NECESSIDADE DE ZELAR PELA LIMPEZA
DAS GARAGENS E CALÇADAS, SENDO ASSIM, A
LIMPEZA SERÁ REALIZADA SEMANALMENTE, PELO APTO
CORRESPONDENTE NA ESCALA.
* QUANDO ORGANIZAR FESTAS NA GARAGEM O APTO
RESPONSÁVEL PELA FESTA, POR FAVOR RETIRAR OS LIXOS RESTANTES.
    </header>
  );
}